In [1]:
import numpy as np

In [2]:
a = np.array(range(9)).reshape(3,3)

In [5]:
print('a: \n' + str(a))

a: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
print('axis 0: {}'.format(np.max(a, axis =0)))
print('axis 1: {}'.format(np.max(a, axis = 1)))

axis 0: [6 7 8]
axis 1: [2 5 8]


In [51]:
new_policy = np.zeros(16)
Q = np.zeros([16, 4])
for state in range(16):
    for action in range(4):
        Q[state][action] += np.random.normal()
new_policy = np.argmax(Q, axis = 1)
new_value_fxn = np.max(Q, axis = 1)

In [53]:
print('Q: {}'.format(Q))

Q: [[-0.28453222 -0.10550173  0.76534994 -0.35684915]
 [ 1.15821519 -0.968518   -1.55001043  0.1711268 ]
 [-0.27844938 -0.10566145 -0.01571092 -1.41535006]
 [ 0.48224506  2.86250589  0.8668819   1.48027733]
 [-0.32472411 -1.73658074  0.23507829  0.01965643]
 [-1.27209837  0.70186496  0.03885979  1.52258452]
 [ 0.32931036  0.71000955 -0.31209782 -0.73396445]
 [-0.77441484 -0.70241656  0.10525777 -0.47933346]
 [-0.77755021 -0.65182899  1.42109961 -1.94362761]
 [-0.19285701 -0.15276761  2.52353519 -1.13479227]
 [-0.68125243 -0.81506536 -0.13468303 -0.72645215]
 [-1.05198802  0.77526515 -0.77031866 -0.15631317]
 [-0.47785681 -0.65792699  0.23504729 -0.25107975]
 [-1.34209256 -1.06164324 -1.22558651  0.64213938]
 [ 1.67036051 -0.30710041 -0.65352296  0.464906  ]
 [-0.83671004  0.01733574 -0.16238235 -0.06628751]]


In [50]:
print('new_policy: {}'.format(new_policy))

new_policy: [1 2 3 3 0 3 1 3 2 1 2 2 2 3 1 3]


In [52]:
print('new_value_fxn: {}'.format(new_value_fxn))

new_value_fxn: [ 0.76534994  1.15821519 -0.01571092  2.86250589  0.23507829  1.52258452
  0.71000955  0.10525777  1.42109961  2.52353519 -0.13468303  0.77526515
  0.23504729  0.64213938  1.67036051  0.01733574]
